version: "3.7"
services:
  nest_app:
    restart: always
    build: .
    environment:
      - APP_PORT=9000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env.docker
    ports:
      - ${PORT}:${PORT}
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
  mysql:
    container_name: ttappsolute-node_mysql
    restart: always
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - ttappsolute-node_mysql_data:/var/lib/mysql
  redis:
    container_name: ttappsolute-node_redis
    restart: always
    image: redis:6.0-alpine
    expose:
      - "6379"
    volumes:
      - ttappsolute-node_redis_data:/data

volumes:
  ttappsolute-node_mysql_data:
  ttappsolute-node_redis_data:

networks:
  ttappsolute-node: